### ISSUE TITLE
Flickering pins on annotation updates

### ISSUE THREAD

**Issue by mrylmz** [hulab/ClusterKit#23]
ClusterKit is causing a flickering issue on custom annotation views using MapKit.

I have tried solving this issue by using: `- addAnnotations(...)` and `- removeAnnotations(...)`,
but that doesn't seam to solve the problem.

I'm calling `- updateClustersIfNeeded` in `-mapView(_:, regionDidChangeAnimated:)` as described in the documentation.

Tested with:
- iOS Version 11.0 GM Seed

**Comment by maxep** [comment]
Thanks for the report @roccx , I've also noticed that flickering on iOS11
I havent found a solution yet.

**Comment by jacogasp** [comment]
I'm using custom annotations views with an animation during the update and running iOS11.
Everything works perfectly but the animation occurs also for clusters/annotations that don't change during the update. 
For me it seems like that during `mapView(_:, regionDidChangeAnimated:)` all the annotations are rebuilt even the ones that should not be updated. Could the flickering related to this?

**Comment by mrylmz** [comment]
I think the issue is that every annotation is replaced by new ones as @JacoGasp says. Isn't there a way to filter annotations by `-isEqual(_:)` or `-hash`?

**Comment by lennartstein** [comment]
I did some debugging and I can say, that the flickering just happens when zooming not when moving the map to west/east/north/south. `mapView(_:, regionDidChangeAnimated:)` just rebuilt the annotations when zooming and moving the map. When moving without zooming it doesn't happen. Maybe there is some issue with the zooming?

**Comment by mrylmz** [comment]
It seems like `MKMapView` is delaying the rendering process of new annotations in some way. Yes I think the annotations are all rebuild because the algorithm instance is getting replaced on zoom. 

I think a solution for that problem would be to manage the annotations in a more smarter way or just delay the removal of the old annotations by 2 or 3 frames.

**Comment by jacogasp** [comment]
@frgmt the refresh occurs to me also panning the map without zooming.

**Comment by maxep** [comment]
The issue appears everytime the clusters are updated, on zoom or significant pan. As @roccx suggested, adding an annotation to `MKMapView` seems to be delayed. The idea would be to update the clusters (replace, expand, collapse) more efficiely. The update is made in the private method `updateMapRect:animated:`, the implementation should be rethink.

**Comment by kkvinokk** [comment]
@maxep is anyone working on the solution for this issue? Please let us know when this is fixed. 

In the time being is there any good alternative to fix this issue?

**Comment by thibauddavid** [comment]
I had the similar problem, and after some research, it happens that ClusterKit reloads each annotations on each pan, rotation etc.
I began to debug the lib, but didn't found any problem in the algorithm which could cause this bug.
As some said above, the underlying problem is that annotation adding are delayed in MKMapView compared to annotation removal (even if they are added before other get removed.)

In my case, the issue was mainly visible because I have several type of annotationViews, on which I update the image depending on type of annotation to display.
As annotationViews got reused, same pin could be reconfigured from a previous recycled pin (with a different image), causing a glitch on each reload.

My workaround consists in having 1 reuseIdentifier per annotation type (including CKCluster), thus configuring my annotationViews only after instantiating them.
As a result, my annotationViews are 100% stable, without any glitch.

Hope that helps !

**Comment by kkvinokk** [comment]
@thibauddavid Thank you for sharing your solution for this issue.

**Comment by maxep** [comment]
I've released a new version : [0.3.0](https://github.com/hulab/ClusterKit/releases/tag/0.3.0) including breaking changes answering this issue.
The clusters' updates and animations are now more efficient and as @thibauddavid described, making a good use of the reusable annotation view is a good practice.

Please check the [CHANGELOG](https://github.com/hulab/ClusterKit/blob/master/CHANGELOG.md)

**Comment by thibauddavid** [comment]
Just read new algorithm, seems much more efficient 🔥
